services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: investment_goals_api
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/yooper
    depends_on:
      - db
    ports:
      - "3000:3000"

  db:
    image: postgres:16
    container_name: investment_goals_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yooper
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
